namespace:
  include:
    pattern: ".*"
  exclude:
    pattern: ""

config:
  discovery:
    services:
      - k8s_namespace: ".*"
        exports: [traces, metrics]
  routes:
    ignored_patterns: ["/health", "/metrics"]
  network:
    enable: true
    cache_active_timeout: 5s
  otel:
    traces_export:
      endpoint: "http://$(OTEL_COLLECTOR_HOST):4318"
    metrics_export:
      endpoint: "http://$(OTEL_COLLECTOR_HOST):4318"